/**
 * Request for the impersonation of another user.
 */
export interface ImpersonateRequest {
  /**
   * The username/email of the impersonator (not the target account that is to be impersonated).
   */
  impersonatorUsernameEmail: string;
  /**
   * The password of the impersonator (not the target account that is to be impersonated).
   */
  impersonatorPassword: string;
  /**
   * The impersonation token initially generated by the admin platform.
   * Acts as a key for looking up the impersonation record which is placed in a shared Redis store.
   * The impersonation record specifies the ID of the impersonator account that is allowed to impersonate,
   * and the ID of the target account that is to be impersonated.
   */
  impersonationToken: string;
}
